spring:
  datasource:
    # 初始化模式，仅能适用于单库 always, embedded and never
    initialization-mode: embedded
    # 数据库初始化建表脚本
#    schema: classpath:db/schema-h2.sql
    # 数据库初始化数据脚本
#    data: classpath:db/data-h2.sql
    # 数据库驱动类
    driver-class-name: org.h2.Driver
    # 数据库地址
    url: jdbc:h2:mem:master
    username: root
    password: test